
# Spring Boot configuration
spring:
  application:
    name: bookstore
  jpa:
    hibernate:
      ddl-auto: create-drop

# Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: mozgi789
    driver-class-name: org.postgresql.Driver