CREATE TABLE IF NOT EXISTS authors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth   DATE,
    surname         VARCHAR(255),
    name            VARCHAR(255),
    patronymic      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS author_book (
    author_id       BIGINT NOT NULL,
    book_id         BIGINT NOT NULL,
    PRIMARY KEY     (author_id, book_id)
);

CREATE TABLE IF NOT EXISTS books (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    number_of_pages INTEGER,
    price           INTEGER,
    release_year    DATE,
    publisher_id    BIGINT
);

CREATE TABLE IF NOT EXISTS genres (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genre_book (
    genre_id        BIGINT NOT NULL,
    book_id         BIGINT NOT NULL,
    PRIMARY KEY     (genre_id, book_id)
);

CREATE TABLE IF NOT EXISTS publishers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login           VARCHAR(255),
    password        VARCHAR(255),
    status          VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users_roles (
    user_id         BIGINT NOT NULL,
    roles_id        BIGINT NOT NULL,
    PRIMARY KEY     (user_id, roles_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamp,
    status          VARCHAR(255),
    user_id         BIGINT
);

CREATE TABLE IF NOT EXISTS order_book (
    order_id        BIGINT NOT NULL,
    book_id         BIGINT NOT NULL,
    PRIMARY KEY     (order_id, book_id)
);

ALTER TABLE IF EXISTS author_book   ADD CONSTRAINT fk_book_id       FOREIGN KEY (book_id)       REFERENCES books;
ALTER TABLE IF EXISTS author_book   ADD CONSTRAINT fk_author_id     FOREIGN KEY (author_id)     REFERENCES authors;
ALTER TABLE IF EXISTS book          ADD CONSTRAINT fk_publisher_id  FOREIGN KEY (publisher_id)  REFERENCES publishers;
ALTER TABLE IF EXISTS genre_book    ADD CONSTRAINT fk_book_id       FOREIGN KEY (book_id)       REFERENCES books;
ALTER TABLE IF EXISTS genre_book    ADD CONSTRAINT fk_genre_id      FOREIGN KEY (genre_id)      REFERENCES genres;
ALTER TABLE IF EXISTS users         ADD CONSTRAINT unique_login     UNIQUE (login);
ALTER TABLE IF EXISTS users_roles   ADD CONSTRAINT fk_user_id       FOREIGN KEY (user_id)       REFERENCES users;
ALTER TABLE IF EXISTS users_roles   ADD CONSTRAINT fk_roles_id      FOREIGN KEY (roles_id)      REFERENCES roles;
ALTER TABLE IF EXISTS orders        ADD CONSTRAINT fk_user_id       FOREIGN KEY (user_id)       REFERENCES users;
ALTER TABLE IF EXISTS order_book    ADD CONSTRAINT fk_book_id       FOREIGN KEY (book_id)       REFERENCES books;
ALTER TABLE IF EXISTS order_book    ADD CONSTRAINT fk_order_id      FOREIGN KEY (order_id)      REFERENCES orders;