CREATE TABLE IF NOT EXISTS author (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth   DATE,
    surname         VARCHAR(255),
    name            VARCHAR(255),
    patronymic      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS author_book (
    author_id   BIGINT NOT NULL,
    book_id     BIGINT NOT NULL,
    PRIMARY KEY (author_id, book_id)
);

CREATE TABLE IF NOT EXISTS book (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    number_of_pages INTEGER,
    price           INTEGER,
    release_year    DATE,
    publisher_id    BIGINT
);

CREATE TABLE IF NOT EXISTS genre (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genre_book (
    genre_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    PRIMARY KEY (genre_id, book_id)
);

CREATE TABLE IF NOT EXISTS publisher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

ALTER TABLE IF EXISTS author_book ADD CONSTRAINT fk_book_id FOREIGN KEY (book_id) REFERENCES book;
ALTER TABLE IF EXISTS author_book ADD CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES author;
ALTER TABLE IF EXISTS book ADD CONSTRAINT fk_publisher_id FOREIGN KEY (publisher_id) REFERENCES publisher;
ALTER TABLE IF EXISTS genre_book ADD CONSTRAINT fk_book_id FOREIGN KEY (book_id) REFERENCES book;
ALTER TABLE IF EXISTS genre_book ADD CONSTRAINT fk_genre_id FOREIGN KEY (genre_id) REFERENCES genre;